name: mediawiki-local

services:
  # MediaWiki instance
  mediawiki:
    container_name: wiki
    image: mediawiki:1.44
    restart: always
    ports:
      - "80:80"
    links:
      - database
    env_file:
      - .env
    volumes:
      - images:/var/www/html/images
      # Important to note is that only the assets folder has been modified and not resources.
      # Otherwise it will mimic what is on the host including missing files.
      - ./resources/assets:/var/www/html/resources/assets
      # Import default and custom skins
      - ./skins:/var/www/html/skins
      # Import extensions, the ones present in the default installation are included
      - ./extensions:/var/www/html/extensions
      # Local exports and imports
      - ./content:/var/www/html/content
      # Import wikitext files
      - ./wikitext_files:/var/www/html/wikitext_files
      # Inject custom LocalSettings.php file
      - ./LocalSettings.php.template:/var/www/html/LocalSettings.php.template
      # Add maintanence scripts
      - ./scripts/setup.sh:/setup.sh
      - ./scripts/update-config.sh:/update-config.sh
      - ./scripts/export-wiki.sh:/export-wiki.sh
      - ./scripts/import-wiki.sh:/import-wiki.sh
      # Inject custom CSS for Citizen
      - ./css:/var/www/html/css
      # Add h5ai for media exports
      - ./_h5ai:/var/www/html/_h5ai
      - ./scripts/setup-h5ai.sh:/setup-h5ai.sh
    environment:
      - MEDIAWIKI_DB_HOST=${MEDIAWIKI_DB_HOST}
      - MEDIAWIKI_DB_NAME=${MEDIAWIKI_DB_NAME}
      - MEDIAWIKI_DB_USER=${MEDIAWIKI_DB_USER}
      - MEDIAWIKI_DB_PASSWORD=${MEDIAWIKI_DB_PASSWORD}
      - MEDIAWIKI_SITENAME=${MEDIAWIKI_SITENAME}
      - MEDIAWIKI_META_NAMESPACE=${MEDIAWIKI_META_NAMESPACE}
      - MEDIAWIKI_SERVER=${MEDIAWIKI_SERVER}
      - MEDIAWIKI_SECRET_KEY=${MEDIAWIKI_SECRET_KEY}
      - MEDIAWIKI_UPGRADE_KEY=${MEDIAWIKI_UPGRADE_KEY}
      - MEDIAWIKI_AUTH_TOKEN_VERSION=${MEDIAWIKI_AUTH_TOKEN_VERSION}
      - MEDIAWIKI_ADMIN_USER=${MEDIAWIKI_ADMIN_USER}
      - MEDIAWIKI_ADMIN_PASS=${MEDIAWIKI_ADMIN_PASS}
    entrypoint:
      [
        "/bin/bash",
        "-c",
        "apt-get update && apt-get install -y default-mysql-client && /setup-h5ai.sh && /setup.sh",
      ]

  # MySQL database used for MediaWiki
  database:
    container_name: db
    image: mysql:9.4
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MEDIAWIKI_DB_NAME}
      MYSQL_USER: ${MEDIAWIKI_DB_USER}
      MYSQL_PASSWORD: ${MEDIAWIKI_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - dbvolume:/var/lib/mysql

volumes:
  dbvolume:
    name: dbvolume
  images: {}
